<?php
//CONSTANTES PARA LISTAS DE MANTENIMIENTO
define("COLOR_LISTA_01","E6DEAC");
define("COLOR_LISTA_02","FFF");
define("COLOR_LISTA_DESCRIPCION","6A948A");

//CONSTANTES PARA LISTA DE MOVIMIENTOS DE CAJA Y BANCOS
define("COLOR_MOV_SALDO","76FFBD");
define("COLOR_MOV_EGRESO","FFD8BD");
define("COLOR_MOV_INGRESO","FFF4BD");


?>